# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_string', models.TextField(unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('valid', models.BooleanField(default=False)),
                ('validation_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorNumber', models.IntegerField()),
                ('steps', models.PositiveIntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='StairWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField(verbose_name='building name ex: ASP, PHS, RMD')),
                ('shaft', models.TextField(verbose_name='a name for the specific stairwell ex: North, South, Main')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steptracker.User')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='stairwell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steptracker.StairWell'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steptracker.User'),
        ),
    ]
