# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steptracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
