# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steptracker', '0002_auto_20171215_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='friday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='monday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='saturday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userstats',
            name='sunday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='thursday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='tuesday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='wednesday_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steptracker.User', unique_for_date='day'),
        ),
    ]
