# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steptracker', '0003_auto_20180109_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
